-- Q1. How many orders has each customer placed?

select c.customer_id , c.customer_name , count(o.order_id) as number_of_orders
from customers as c
left join orders as o
on c.customer_id = o.customer_id
group by c.customer_id , c.customer_name;

-- Q2. Which customers have placed more than one order?
select c.customer_id , c.customer_name , count(o.order_id) as number_of_orders
from customers as c
inner join orders as o
on c.customer_id = o.customer_id
group by c.customer_id , c.customer_name
having number_of_orders > 1;

-- Q3. What is the total amount spent by each customer?
select c.customer_id , c.customer_name , sum(p.amount) as total_amount
from customers as c
join orders as o
on c.customer_id = o.customer_id
join payments as p
on o.order_id = p.order_id
group by  c.customer_id , c.customer_name;

-- Q4. Which customers have spent more than ₹10,000?
select c.customer_id , c.customer_name , sum(p.amount) as total_amount
from customers as c
join orders as o
on c.customer_id = o.customer_id
join payments as p
on o.order_id = p.order_id
group by  c.customer_id , c.customer_name
having total_amount > 10000;

-- Q5. What is the total revenue generated by each product?
select p.product_id , p.product_name , sum(p.price * oi.quantity) as total_revenue
from products as p
join order_items as oi
on p.product_id = oi.product_id
group by  p.product_id , p.product_name;

-- Q6. Which product generated the highest revenue?
select p.product_id , p.product_name , sum(p.price * oi.quantity) as highest_revenue
from products as p
join order_items as oi
on p.product_id = oi.product_id
group by  p.product_id , p.product_name
order by highest_revenue desc
limit 1;

-- Q7. What is the total revenue generated by each product category?
select p.category , sum(p.price * oi.quantity) as total_revenue
from products as p
join order_items as oi
on p.product_id = oi.product_id
group by p.category;

-- Q8. How much revenue did each seller generate?
select s.seller_id , s.seller_name , sum(p.price * oi.quantity) as total_revenue
from sellers as s
join products as p
on s.seller_id = p.seller_id
join order_items as oi
on oi.product_id = p.product_id
group by s.seller_id,s.seller_name;

-- Q9. How many orders are there in each order status?
select order_status , count(order_id) as number_of_order
from orders
group by order_status;

-- Q10. Which payment method is used most frequently?
select payment_type , count(payment_id) as number_of_times
from payments
group by payment_type
order by number_of_times desc
limit 1;