-- Q1. Which product has been ordered the most by quantity?
select p.product_id , p.product_name , sum(oi.quantity) as total_quantity
from products as p
join order_items as oi
on p.product_id = oi.product_id
group by p.product_id , p.product_name
order by total_quantity desc
limit 1;

-- Q2. Which product has generated the highest revenue in each category?
with 
total_revenue as(
select p.category , p.product_name , sum(p.price * oi.quantity) as tot_revenue 
from products as p
join order_items as oi
on p.product_id = oi.product_id
group by p.category , p.product_name) ,
ranked_products as (
	select category , product_name , tot_revenue , 
    rank() over(partition by category order by tot_revenue desc) as revenue_rank
    from total_revenue
)
select category , product_name , tot_revenue as highest_revenue
from ranked_products
where  revenue_rank = 1;

-- Q3. Which seller has sold the highest number of products?
select s.seller_id ,  s.seller_name , sum(oi.quantity) as quantity_sold
from sellers as s
join products as p
on s.seller_id = p.seller_id
join order_items as oi
on oi.product_id = p.product_id
group by s.seller_id , s.seller_name
order by quantity_sold desc
limit 1;

-- Q4. Which customers have placed the highest number of orders?
with number_of_orders as(
select c.customer_id , c.customer_name , count(o.order_id) as no_of_orders
from customers as c
join orders as o
on c.customer_id = o.customer_id
group by c.customer_id ,c.customer_name)

select customer_id , customer_name , no_of_orders 
from number_of_orders 
where no_of_orders = (select max(no_of_orders) from number_of_orders);

-- Q5. Which month generated the highest revenue?
select monthname(o.order_date) as order_month, sum(p.price * oi.quantity) as revenue
from products as p
join order_items as oi
on p.product_id = oi.product_id
join orders as o
on o.order_id = oi.order_id
group by monthname(o.order_date) 
order by revenue desc
limit 1;

-- Q6. What is the total revenue generated by each seller type?
select s.seller_type, sum(p.price * oi.quantity) as total_revenue
from sellers as s
join products as p
on s.seller_id = p.seller_id
join order_items as oi
on p.product_id = oi.product_id
group by s.seller_type;


-- Q7. Which payment method generated the highest total revenue?
create or replace view payment_method_revenue as
 select pa.payment_type , sum(oi.quantity * p.price) as total_revenue
 from products as p
 join order_items as oi
 on p.product_id = oi.product_id
 join payments as pa
 on pa.order_id = oi.order_id
 group by payment_type;

select payment_type , total_revenue as highest_total_revenue
from payment_method_revenue
order by total_revenue desc
limit 1; 

-- Q8. Customers who spent more than the average customer spend 
create or replace view Customer_spending
as select  c.customer_id, c.customer_name , sum(oi.quantity * p.price) AS customer_spending
from customers as c
join orders as o
on c.customer_id = o.customer_id
join order_items as oi
on o.order_id = oi.order_id
join products as p
on oi.product_id = p.product_id
group by c.customer_id , c.customer_name ;

select c.customer_id , c.customer_name , round(sum(oi.quantity * p.price)) as total_spending
from customers as c
join orders as o
on c.customer_id = o.customer_id
join order_items as oi
on o.order_id = oi.order_id
join products as p
on oi.product_id = p.product_id
group by c.customer_id , c.customer_name
having total_spending > (
select avg(customer_spending) from Customer_spending);

-- Q9. Spending classification using CASE
select customer_id , customer_name , customer_spending ,
case 
	when customer_spending >= 10000 then "High Spending"
    when customer_spending >= 5000 then "Medium Spending"
    else "Low Spending"
end as spending_category
from customer_spending;

-- Q10. Display all orders placed by a particular customer
delimiter //
create procedure get_customer_orders(in input_customer_id int)
begin 
	select order_id , customer_id , order_date , order_status
    from orders
    where customer_id = input_customer_id
    order by order_date;
end //

delimiter ;

call get_customer_orders(1);

